name: Firmware image generation
on: [push]
jobs:
  build:
    env:
     otp-version: OTP-27.0.1
     elixir-version: v1.17.2-otp-27
     nerves_bootstrsap_version:  1.13.0
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt install build-essential automake autoconf git squashfs-tools pkgconf curl libmnl-dev -y
      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: Install nerves_bootstrap
        run: |
          mix archive.install --force hex nerves_bootstrap ${{ env.nerves_bootstrsap_version }}
      - name: Build
        run: |
          mkdir -p deploy/artifacts
          MIX_TARGET=superbird mix deps.get
          MIX_TARGET=superbird mix firmware --output deploy/artifacts
      - name: Upload Artifacts
        if: contains(github.ref, 'tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/artifacts
          file_glob: true
          tag: ${{ github.ref }}

